repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: http://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - "--extra-keys=cell.metadata.pycharm"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==3.3.1]
        args: [--py39-plus]
      - id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
        args: [--float-to-top]
      - id: nbqa-black
        additional_dependencies: [black==23.1.0]
        args: [--target-version=py39]
      - id: nbqa-flake8
        additional_dependencies: [flake8==6.0.0]

default_language_version:
  python: python3
