repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-toml
    - id: check-symlinks
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

  - repo: http://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-blanket-type-ignore
    - id: python-no-eval
    - id: python-no-log-warn
    - id: python-use-type-annotations

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      - id: nbqa-pyupgrade
        args: [--py39-plus]
      - id: nbqa-isort
      - id: nbqa-black
        args: [--target-version=py39]
      - id: nbqa-flake8

default_language_version:
  python: python3
