repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]
        types: [python]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--target-version=py39]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: http://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/pycqa/pylint
    rev: v2.16.0
    hooks:
      - id: pylint
        language: system
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        language: system
        types: [python]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - "--extra-keys=cell.metadata.pycharm"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-pyupgrade
        args: [--py39-plus]
        additional_dependencies: [pyupgrade==3.3.1]
      - id: nbqa-isort
        args: [--float-to-top]
        additional_dependencies: [isort==5.12.0]
      - id: nbqa-black
        args: [--target-version=py39]
        additional_dependencies: [black==23.1.0]
      - id: nbqa-flake8
        args: ["--extend-ignore=F401,E501"]
        additional_dependencies: [flake8==6.0.0]

  - repo: local
    hooks:
      - id: pytest
        entry: pytest
        language: system
        pass_filenames: false
        name: pytest
        types: [python]

default_language_version:
  python: python3
