version: "3.8"

services:

  predict:
    build:
      context: .
      dockerfile: predict/dockerfile
      target: predict
    platform: linux/x86_64

  predict.test:
    build:
      context: .
      dockerfile: predict/dockerfile
      target: predict.test
    platform: linux/x86_64
