version: "3.8"

x-hashicorp-config: &hashicorp-config
  CONSUL_ADDR: "${CONSUL_ADDR}"
  NOMAD_ADDR: "${NOMAD_ADDR}"
  VAULT_ADDR: "${VAULT_ADDR}"
  VAULT_TOKEN: "${VAULT_TOKEN}"
  DEPLOY_CONFIG: "${DEPLOY_CONFIG}"
  VERSION: "${VERSION}"

services:

  # render all nomad jobs and output them to ./nomad/
  render:
    environment:
      <<: *hashicorp-config
      DEPLOY: "FALSE"
    image: ghcr.io/pennsignals/deploy_action/deploy_action.deploy:0.1.3
    volumes:
    - ./:/source
    working_dir: /source

  # render all nomad jobs and deploy them
  deploy:
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/deploy_action/deploy_action.deploy:0.1.3
    volumes:
    - ./:/source
    working_dir: /source

  # upload all config files to consul
  config:
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/consul_configs_submit_action/consul_configs_submit_action.consul:1.0.0
    volumes:
    - ./:/source/
    working_dir: /source

  # get secrets from vault
  secrets_get:
    command:
    - "--get"
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/secrets/secrets.vault:1.2.0
    volumes:
    - ./:/source/
    working_dir: /source

  # put secrets to vault
  secrets_put:
    command:
    - "--put"
    environment:
      <<: *hashicorp-config
    image: ghcr.io/pennsignals/secrets/secrets.vault:1.2.0
    volumes:
    - ./:/source/
    working_dir: /source
