name: release
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: version
        run: |
          version=$(./scripts/version.sh)
          echo "version = ${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - id: publish
        run: |
          ./scripts/publish.sh -b true -p "${{ secrets.GITHUB_TOKEN }}" -v "${{ steps.version.outputs.version }}"

  evaluation:
    if: ${{ github.event.release.prerelease }}
    needs: publish
    runs-on: [evaluation, self-hosted, nomad, azure]

    steps:
      - id: checkout
        uses: actions/checkout@v4

        # Deploy configuration
      - id: consul
        run: |
          ./scripts/consul.sh \
            --src ./predict/local/configuration.yaml \
            --dst pennsignals/{{ cookiecutter.name }}/predict/configuration.yaml

        # Deploy jobs
      - id: nomad
        run: |
          ./scripts/nomad.sh \
            --src ./predict/nomad \
            --dst ./nomad \
            --version "${{ needs.publish.outputs.version }}"

      # Upload rendered nomad jobs as artifacts
      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: nomad
          path: nomad.tar.gz

      # Add artifacts to release
      - id: release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: nomad.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  production:
    if: ${{ !github.event.release.prerelease }}
    needs: publish
    runs-on: [self-hosted, nomad, azure, production]

    steps:
      - id: checkout
        uses: actions/checkout@v4

        # Deploy configuration
      - id: consul
        run: |
          ./scripts/consul.sh \
            --src ./predict/local/configuration.yaml \
            --dst pennsignals/{{ cookiecutter.name }}/predict/configuration.yaml

        # Deploy jobs
      - id: nomad
        run: |
          ./scripts/nomad.sh \
            --src ./predict/nomad
            --dst ./nomad \
            --version "${{ needs.publish.outputs.version }}"

      # Upload rendered nomad jobs as artifacts
      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: nomad
          path: nomad.tar.gz

      # Add artifacts to release
      - id: release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: nomad.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
