{% raw %}
name: test

on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: test
      run: |
        # login in case there are any images as dependencies
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

        docker-compose run predict.test
{% endraw %}
