{% raw %}name: test

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  predict:
    name: predict.test ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - "3.9"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          docker compose build --build-arg PYTHON_VERSION=${{ matrix.target }} predict.test

      - name: test
        run: |
          docker compose run predict.test

  jupyterlab:
    name: jupyterlab.test ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - "3.9"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          docker compose build --build-arg PYTHON_VERSION=${{ matrix.target }} jupyterlab{% endraw %}
