name: test

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup_python${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: test
        run: |
          pip install -U setuptools wheel pip
          pip install cruft pre-commit
          pre-commit run --all-files
          echo "--checkout ${{ github.ref_name }}"
          echo "--directory ${{ github.event.repository.name }}canary"
          echo "https://github.com/${{ github.repository }}"
          cruft create \
            --no-input \
            --checkout ${{ github.ref_name }} \
            --directory ${{ github.event.repository.name }}canary \
            https://github.com/${{ github.repository }}
          ls -al
          cd ${{ github.event.repository.name }}canary
          git config --global init.defaultBranch main
          git init .
          git remote add origin https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}canary.git
          git add -A
          git config user.email ${{ secrets.username }}@users.noreply.github.com
          git config user.name ${{ secrets.username }}
          git config credential.helper store
          git commit -m 'Canary'
          if [ "${{ github.event.repository.name }}" != "servicetemplate" ]; then
            exit;
          fi
          (echo protocol=https; echo host=github.com; echo username=pennsignals123; echo password=$(printf '${{ secrets.pat }}' | jq -sRr @uri); echo) | git credential approve
          git push -u origin main -f -v
