name: test

on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.9", "3.10"]

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup_python${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: test
      run: |
        # login in case there are any images as dependencies
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        pip install -U setuptools wheel pip
        pip install cruft pre-commit
        pre-commit run --all-files
        cruft create --no-input ${{ github.repository }}
        cd example
        docker-compose run predict.test
