name: test

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup_python${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup
        run: |
          pip install -U setuptools wheel pip
          pip install cruft pre-commit

      - name: pre-commit
        run: |
          pre-commit run --all-files

      - name: cruft
        run: |
          ./scripts/cruft.sh \
            --branch ${{ github.ref_name }} \
            --name ${GITHUB_REPOSITORY#*/} \
            --organization ${GITHUB_REPOSITORY%/*} \
            --username ${{ secrets.username }}

      - name: push
        if: ${GITHUB_REPOSITORY%/*} == "servicetemplate"
        run: |
          ./scripts/push.sh \
            --branch ${{ github.ref_name }} \
            --name ${GITHUB_REPOSITORY#*/} \
            --organization ${GITHUB_REPOSITORY%/*} \
            --password ${{ secrets.pat }}
            --username ${{ secrets.username }} \
